#include <convex_codegen/emit.h>

#include <gtest/gtest.h>

#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>

namespace fs = std::filesystem;

namespace {

std::string read_text(const fs::path& path) {
    std::ifstream in(path, std::ios::binary);
    std::ostringstream buf;
    buf << in.rdbuf();
    return buf.str();
}

bool contains(const std::string& haystack, const std::string& needle) {
    return haystack.find(needle) != std::string::npos;
}

std::map<std::string, std::string> emit_fixture(const convex_codegen::emit_options& opts) {
    return convex_codegen::emit_all(read_text(FIXTURE_PATH), opts);
}

}  // namespace

TEST(Emit, HeaderProvenance) {
    convex_codegen::emit_options opts;
    opts.stamp = "// STAMP LINE";
    auto files = emit_fixture(opts);
    EXPECT_EQ(files.at("ConvexApi.h").rfind("// Generated by convex-ue-codegen. Do not edit by hand.\n// STAMP LINE\n", 0), 0u);
}

TEST(Emit, SourceLabelWhenNoStamp) {
    convex_codegen::emit_options opts;
    opts.source_label = "https://x.convex.cloud";
    auto files = emit_fixture(opts);
    EXPECT_TRUE(contains(files.at("ConvexApi.h"), "// Source: https://x.convex.cloud\n"));
}

TEST(Emit, NestedNamespaceForSlashModule) {
    auto files = emit_fixture({});
    const std::string& h = files.at("ConvexApi.h");
    EXPECT_TRUE(contains(h, "namespace Admin\n{\nnamespace Tools\n{"));
}

TEST(Emit, QueryGetsWatchVariant) {
    auto files = emit_fixture({});
    const std::string& h = files.at("ConvexApi.h");
    // noArgs is a Query -> both one-shot and Watch wrappers.
    EXPECT_TRUE(contains(h, "void NoArgs(UConvexClient& Client, FConvexResultNative OnResult);"));
    EXPECT_TRUE(contains(h, "UConvexSubscription* WatchNoArgs(UConvexClient& Client, FConvexResultNative OnUpdate);"));
}

TEST(Emit, MutationHasNoWatch) {
    auto files = emit_fixture({});
    const std::string& h = files.at("ConvexApi.h");
    EXPECT_FALSE(contains(h, "WatchReset"));
}

TEST(Emit, PaginatedQueryGetsPaginatedWatchVariant) {
    auto files = emit_fixture({});
    const std::string& h = files.at("ConvexApi.h");
    const std::string& c = files.at("ConvexApi.cpp");
    // messages:listPaginated matches the paginationOpts shape. It keeps its
    // plain X + WatchX wrappers (paginationOpts stays an ordinary arg there)
    // and gains a WatchXPaginated wrapper that drops paginationOpts and takes
    // InitialNumItems + FConvexPaginatedUpdateNativeFn.
    EXPECT_TRUE(contains(h, "void ListPaginated(UConvexClient& Client, const FString& Channel, const FConvexValue& PaginationOpts, FConvexResultNative OnResult);"));
    EXPECT_TRUE(contains(h, "UConvexSubscription* WatchListPaginated(UConvexClient& Client, const FString& Channel, const FConvexValue& PaginationOpts, FConvexResultNative OnUpdate);"));
    EXPECT_TRUE(contains(h, "UConvexPaginatedSubscription* WatchListPaginatedPaginated(UConvexClient& Client, const FString& Channel, int32 InitialNumItems, FConvexPaginatedUpdateNativeFn OnUpdate);"));
    // The paginated impl injects paginationOpts via the client entry point.
    EXPECT_TRUE(contains(c, "return Client.SubscribePaginatedNative(TEXT(\"messages:listPaginated\"), Args, InitialNumItems, MoveTemp(OnUpdate));"));
    // Its Args map must NOT carry paginationOpts (the client injects it).
    const std::size_t pag = c.find("WatchListPaginatedPaginated(UConvexClient& Client");
    ASSERT_NE(pag, std::string::npos);
    const std::size_t body_end = c.find("\n}", pag);
    EXPECT_EQ(c.substr(pag, body_end - pag).find("paginationOpts"), std::string::npos);
}

TEST(Emit, PaginatedIncludesPluginHeader) {
    auto files = emit_fixture({});
    // The header pulls in ConvexPaginatedSubscription.h for the alias/type.
    EXPECT_TRUE(contains(files.at("ConvexApi.h"), "#include \"ConvexPaginatedSubscription.h\""));
}

TEST(Emit, NonMatchingPaginationOptsGetsNoPaginatedVariant) {
    auto files = emit_fixture({});
    const std::string& h = files.at("ConvexApi.h");
    // messages:listBad has a paginationOpts arg missing `cursor`: it is a plain
    // query (X + WatchX) and must NOT get a paginated wrapper.
    EXPECT_TRUE(contains(h, "UConvexSubscription* WatchListBad(UConvexClient& Client, const FString& Channel, const FConvexValue& PaginationOpts, FConvexResultNative OnUpdate);"));
    EXPECT_FALSE(contains(h, "WatchListBadPaginated"));
}

TEST(Emit, PassthroughForAnyArgs) {
    auto files = emit_fixture({});
    const std::string& c = files.at("ConvexApi.cpp");
    // anyArgs (args: any) -> single TMap pass-through, forwarded directly.
    EXPECT_TRUE(contains(c, "void ConvexApi::Sink::AnyArgs(UConvexClient& Client, const TMap<FString, FConvexValue>& Args, FConvexResultNative OnResult)"));
    EXPECT_TRUE(contains(c, "Client.MutationNative(TEXT(\"sink:anyArgs\"), Args, MoveTemp(OnResult));"));
}

TEST(Emit, OptionalArgUsesTOptionalAndGuard) {
    auto files = emit_fixture({});
    const std::string& h = files.at("ConvexApi.h");
    const std::string& c = files.at("ConvexApi.cpp");
    // runAction has an optional 'count' number and a required 'uploadId' id.
    EXPECT_TRUE(contains(h, "const TOptional<double>& Count"));
    EXPECT_TRUE(contains(h, "const FString& /* Id<uploads> */ UploadId"));
    EXPECT_TRUE(contains(c, "if (Count.IsSet())"));
    EXPECT_TRUE(contains(c, "Args.Add(TEXT(\"count\"), FConvexValue::Float(Count.GetValue()));"));
}

TEST(Emit, IdCommentAndActionNative) {
    auto files = emit_fixture({});
    const std::string& c = files.at("ConvexApi.cpp");
    EXPECT_TRUE(contains(c, "Client.ActionNative(TEXT(\"sink:runAction\")"));
    EXPECT_TRUE(contains(c, "Args.Add(TEXT(\"uploadId\"), FConvexValue::String(UploadId));"));
}

TEST(Emit, ScalarArrayLoop) {
    auto files = emit_fixture({});
    const std::string& c = files.at("ConvexApi.cpp");
    EXPECT_TRUE(contains(c, "for (const FString& _Item : Tags)"));
    EXPECT_TRUE(contains(c, "_TagsItems.Add(FConvexValue::String(_Item));"));
    EXPECT_TRUE(contains(c, "Args.Add(TEXT(\"tags\"), FConvexValue::Array(_TagsItems));"));
}

TEST(Emit, BlueprintClassAndCategory) {
    auto files = emit_fixture({});
    const std::string& h = files.at("ConvexApiBP.h");
    EXPECT_TRUE(contains(h, "class UConvexApiSinkLibrary : public UBlueprintFunctionLibrary"));
    EXPECT_TRUE(contains(h, "Category = \"Convex API|sink\""));
    EXPECT_TRUE(contains(h, "DisplayName = \"Convex sink:kitchenSink\""));
    // generated.h must be included.
    EXPECT_TRUE(contains(h, "#include \"ConvexApiBP.generated.h\""));
}

TEST(Emit, BlueprintOmitsOptionalArgs) {
    auto files = emit_fixture({});
    const std::string& h = files.at("ConvexApiBP.h");
    // BP RunAction keeps required uploadId (as FString) but drops optional count.
    EXPECT_TRUE(contains(h, "static void RunAction(UConvexClient* Client, const FString& UploadId, FConvexResultDelegate OnResult);"));
    EXPECT_TRUE(contains(h, "optional args omitted; use the C++ wrapper"));
}

TEST(Emit, BlueprintNullGuard) {
    auto files = emit_fixture({});
    const std::string& c = files.at("ConvexApiBP.cpp");
    EXPECT_TRUE(contains(c, "if (Client == nullptr)"));
    EXPECT_TRUE(contains(c, "DEFINE_LOG_CATEGORY_STATIC(LogConvexApiBP, Log, All);"));
}

TEST(Emit, BlueprintBodyOmitsOptionalArgs) {
    // admin/tools:reset has a single optional 'force' arg. The BP wrapper drops
    // it from the signature, so its body must NOT reference a 'Force' parameter.
    auto files = emit_fixture({});
    const std::string& c = files.at("ConvexApiBP.cpp");
    const std::size_t reset = c.find("UConvexApiAdminToolsLibrary::Reset");
    ASSERT_NE(reset, std::string::npos);
    const std::size_t body_end = c.find("\n}", reset);
    const std::string body = c.substr(reset, body_end - reset);
    EXPECT_EQ(body.find("Force"), std::string::npos) << "BP body references dropped optional arg";
    EXPECT_NE(body.find("Client->Mutation(TEXT(\"admin/tools:reset\"), Args, OnResult);"),
              std::string::npos);
}

TEST(Emit, NameCollisionDeduplicated) {
    // foo_bar:x and fooBar:x collide into namespace/class FooBar; the second
    // (by canonical id sort) becomes X_2 / WatchX_2.
    auto files = emit_fixture({});
    const std::string& h = files.at("ConvexApi.h");
    EXPECT_TRUE(contains(h, "void X(UConvexClient& Client, const FString& A, FConvexResultNative OnResult);"));
    EXPECT_TRUE(contains(h, "void X_2(UConvexClient& Client, const FString& A, FConvexResultNative OnResult);"));
    EXPECT_TRUE(contains(h, "WatchX_2"));
}

TEST(Emit, ModuleScaffolding) {
    convex_codegen::emit_options opts;
    opts.emit_module = "MyConvexApi";
    auto files = emit_fixture(opts);
    ASSERT_TRUE(files.count("MyConvexApi.Build.cs"));
    ASSERT_TRUE(files.count("MyConvexApiModule.cpp"));
    EXPECT_TRUE(contains(files.at("MyConvexApi.Build.cs"), "public class MyConvexApi : ModuleRules"));
    EXPECT_TRUE(contains(files.at("MyConvexApi.Build.cs"), "\"ConvexClient\""));
    EXPECT_TRUE(contains(files.at("MyConvexApi.Build.cs"), "\"ConvexCore\""));
    EXPECT_TRUE(contains(files.at("MyConvexApiModule.cpp"), "IMPLEMENT_MODULE(FDefaultModuleImpl, MyConvexApi);"));
    // Without the flag, only the 4 API files are emitted.
    EXPECT_EQ(emit_fixture({}).size(), 4u);
}

TEST(Emit, ScriptWrappersOptIn) {
    // Off by default: the .as file only appears with emit_script.
    EXPECT_FALSE(emit_fixture({}).count("ConvexApi.as"));
    convex_codegen::emit_options opts;
    opts.emit_script = true;
    auto files = emit_fixture(opts);
    ASSERT_TRUE(files.count("ConvexApi.as"));
    const std::string& as = files.at("ConvexApi.as");
    // Nested namespaces under the prefix, no C++ includes or macros.
    EXPECT_TRUE(contains(as, "namespace ConvexApi::Admin::Tools\n{"));
    EXPECT_FALSE(contains(as, "#include"));
    EXPECT_FALSE(contains(as, "GENERATED_BODY"));
    // Script types: 64-bit float, references instead of pointers, delegates
    // for callbacks, and the ScriptCallable client methods.
    EXPECT_TRUE(contains(as, "void X(UConvexClient Client, FString A, FConvexResultDelegate OnResult)"));
    EXPECT_TRUE(contains(as, "UConvexSubscription WatchX(UConvexClient Client, FString A, FConvexResultDelegate OnUpdate)"));
    EXPECT_TRUE(contains(as, "Client.Query(\"fooBar:x\", _Args, OnResult);"));
    EXPECT_TRUE(contains(as, "return Client.Subscribe(\"fooBar:x\", _Args, OnUpdate);"));
    EXPECT_TRUE(contains(as, "Convex::MakeConvexString(A)"));
    EXPECT_FALSE(contains(as, "TOptional"));
    EXPECT_FALSE(contains(as, "double"));
    EXPECT_FALSE(contains(as, "UConvexClient*"));
    // Paginated queries get the live-list wrapper on the client's script API.
    // The fixture's paginated query declares its page shape, so the wrapper
    // takes the typed page delegate and routes through an adapter.
    EXPECT_TRUE(contains(as, "UConvexPaginatedSubscription WatchListPaginatedPaginated("));
    EXPECT_TRUE(contains(as, "int InitialNumItems, FConvexApiMessagesListPaginatedPageDelegate OnUpdate)"));
    EXPECT_TRUE(contains(as, "UConvexPaginatedSubscription _Subscription = Client.SubscribePaginated(\"messages:listPaginated\", _Args, InitialNumItems, _Handler);"));
}

TEST(Emit, ScriptStructsDedupeByShape) {
    convex_codegen::emit_options opts;
    opts.emit_script = true;
    const std::string as = emit_fixture(opts).at("ConvexApi.as");
    // messages:list returns array<doc> and messages:listPaginated returns a
    // page of the same doc shape: one struct, named after the first function
    // in sorted order, an array return naming its element "Element".
    EXPECT_TRUE(contains(as, "struct FConvexApiMessagesListElement\n{"));
    EXPECT_FALSE(contains(as, "struct FConvexApiMessagesListPaginatedResultPageElement"));
    EXPECT_TRUE(contains(as, "TArray<FConvexApiMessagesListElement> Page;"));
    // An object return is "<Base>Result"; nested objects append the field.
    EXPECT_TRUE(contains(as, "struct FConvexApiSinkKitchenSinkResult\n{"));
    EXPECT_TRUE(contains(as, "struct FConvexApiSinkKitchenSinkNested\n{"));
    EXPECT_TRUE(contains(as, "struct FConvexApiSinkKitchenSinkNestedDeep\n{"));
    EXPECT_TRUE(contains(as, "struct FConvexApiSinkKitchenSinkItemsElement\n{"));
    // Members: script float for number, string for id, system fields lose
    // their leading underscore like every other PascalCased name, and the
    // shape line documents the wire names.
    EXPECT_TRUE(contains(as, "/// object{ _creationTime: number, _id: id<messages>, author: string, body: string, channel: string, edited?: boolean }"));
    EXPECT_TRUE(contains(as, "\tfloat CreationTime = 0.0;\n"));
    EXPECT_TRUE(contains(as, "\tFString Id;\n"));
    EXPECT_TRUE(contains(as, "Out.Id = Value.Get(\"_id\").AsString();"));
    // Decode and Encode live in the Types namespace; Encode overloads by struct.
    EXPECT_TRUE(contains(as, "namespace ConvexApi::Types\n{"));
    EXPECT_TRUE(contains(as, "FConvexApiMessagesListElement DecodeMessagesListElement(FConvexValue Value)"));
    EXPECT_TRUE(contains(as, "FConvexValue Encode(FConvexApiMessagesListElement In)"));
    EXPECT_TRUE(contains(as, "Out.Author = Value.Get(\"author\").AsString();"));
    EXPECT_TRUE(contains(as, "Fields.Add(\"author\", Convex::MakeConvexString(In.Author));"));
    // A nested struct decodes through its own function, qualified.
    EXPECT_TRUE(contains(as, "Out.Deep = ConvexApi::Types::DecodeSinkKitchenSinkNestedDeep(Value.Get(\"deep\"));"));
    EXPECT_TRUE(contains(as, "Fields.Add(\"deep\", ConvexApi::Types::Encode(In.Deep));"));
}

TEST(Emit, ScriptOptionalStructFieldsGetHasFlag) {
    convex_codegen::emit_options opts;
    opts.emit_script = true;
    const std::string as = emit_fixture(opts).at("ConvexApi.as");
    EXPECT_TRUE(contains(as, "\tbool Edited = false;\n\tbool bHasEdited = false;"));
    EXPECT_TRUE(contains(as, "\t\tif (Value.HasField(\"edited\"))\n\t\t{\n\t\t\tOut.bHasEdited = true;\n\t\t\tOut.Edited = Value.Get(\"edited\").AsBool();\n\t\t}\n"));
    EXPECT_TRUE(contains(as, "\t\tif (In.bHasEdited)\n\t\t{\n\t\t\tFields.Add(\"edited\", Convex::MakeConvexBool(In.Edited));\n\t\t}\n"));
}

TEST(Emit, ScriptTypedReturnsUseDelegateAndAdapter) {
    convex_codegen::emit_options opts;
    opts.emit_script = true;
    const std::string as = emit_fixture(opts).at("ConvexApi.as");
    // Object return.
    EXPECT_TRUE(contains(as, "delegate void FConvexApiSinkKitchenSinkDelegate(FConvexApiSinkKitchenSinkResult Value, FConvexResult Result);"));
    EXPECT_TRUE(contains(as, "class UConvexApiSinkKitchenSinkAdapter : UObject\n{"));
    EXPECT_TRUE(contains(as, "Value = ConvexApi::Types::DecodeSinkKitchenSinkResult(Result.Value);"));
    EXPECT_TRUE(contains(as, "Typed.ExecuteIfBound(Value, Result);"));
    // Array return decodes element by element.
    EXPECT_TRUE(contains(as, "delegate void FConvexApiMessagesListDelegate(TArray<FConvexApiMessagesListElement> Value, FConvexResult Result);"));
    EXPECT_TRUE(contains(as, "Value.Add(ConvexApi::Types::DecodeMessagesListElement(_Item));"));
    // Scalar return.
    EXPECT_TRUE(contains(as, "delegate void FConvexApiCountersGetDelegate(float Value, FConvexResult Result);"));
    EXPECT_TRUE(contains(as, "\t\tfloat Value = 0.0;\n\t\tif (Result.bSuccess)\n\t\t{\n\t\t\tValue = Result.Value.AsFloat();\n\t\t}\n"));
    // Wrappers: one-shot binds the adapter and hands the raw delegate to the
    // client, which roots the adapter until the callback fires; a watch
    // attaches the adapter to the subscription instead.
    EXPECT_TRUE(contains(as, "void Get(UConvexClient Client, FString Name, FConvexApiCountersGetDelegate OnResult)"));
    EXPECT_TRUE(contains(as, "UConvexApiCountersGetAdapter _Adapter = Cast<UConvexApiCountersGetAdapter>(NewObject(Client, UConvexApiCountersGetAdapter));"));
    EXPECT_TRUE(contains(as, "_Adapter.Typed = OnResult;\n\t\tFConvexResultDelegate _Handler;\n\t\t_Handler.BindUFunction(_Adapter, n\"OnResult\");\n\t\tClient.Query(\"counters:get\", _Args, _Handler);"));
    EXPECT_TRUE(contains(as, "UConvexSubscription _Subscription = Client.Subscribe(\"counters:get\", _Args, _Handler);\n\t\tif (_Subscription != nullptr)\n\t\t{\n\t\t\t_Subscription.AttachListener(_Adapter);\n\t\t}\n\t\treturn _Subscription;"));
    // Paginated page adapter decodes the snapshot items.
    EXPECT_TRUE(contains(as, "delegate void FConvexApiMessagesListPaginatedPageDelegate(TArray<FConvexApiMessagesListElement> Results, FConvexPaginatedSnapshot Snapshot);"));
    EXPECT_TRUE(contains(as, "void OnSnapshot(FConvexPaginatedSnapshot Snapshot)"));
    EXPECT_TRUE(contains(as, "_Handler.BindUFunction(_Adapter, n\"OnSnapshot\");"));
    // A function without a declared return keeps the raw delegate and no adapter.
    EXPECT_TRUE(contains(as, "void X(UConvexClient Client, FString A, FConvexResultDelegate OnResult)"));
    EXPECT_FALSE(contains(as, "UConvexApiFooBarXAdapter"));
}

TEST(Emit, ScriptObjectArgsAreStructs) {
    convex_codegen::emit_options opts;
    opts.emit_script = true;
    const std::string as = emit_fixture(opts).at("ConvexApi.as");
    // Object-typed args (nested, arrays of objects) take the struct; the body
    // encodes them. Unions, records, and any stay FConvexValue.
    EXPECT_TRUE(contains(as, "TArray<FConvexApiSinkKitchenSinkItemsElement> Items,"));
    EXPECT_TRUE(contains(as, "_ItemsItems.Add(ConvexApi::Types::Encode(_Item));"));
    EXPECT_TRUE(contains(as, "_Args.Add(\"nested\", ConvexApi::Types::Encode(Nested));"));
    EXPECT_TRUE(contains(as, "FConvexValue Rec, FString S, TArray<FString> Tags, FConvexValue Uni,"));
    // An empty object and nested containers stay FConvexValue.
    EXPECT_FALSE(contains(as, "TArray<TArray"));
}

TEST(Emit, ScriptOptionalArgsBecomeOverloads) {
    convex_codegen::emit_options opts;
    opts.emit_script = true;
    const std::string as = emit_fixture(opts).at("ConvexApi.as");
    // A function with optional fields is emitted twice: required-only and
    // all-arguments, the second marked by its doc line.
    EXPECT_TRUE(contains(as, "/// All arguments, including the optional ones."));
    const std::size_t first = as.find("void Reset(UConvexClient Client, FConvexResultDelegate OnResult)");
    const std::size_t full = as.find("void Reset(UConvexClient Client, bool Force, FConvexResultDelegate OnResult)");
    ASSERT_NE(first, std::string::npos);
    ASSERT_NE(full, std::string::npos);
    EXPECT_LT(first, full);
    EXPECT_TRUE(contains(as, "_Args.Add(\"force\", Convex::MakeConvexBool(Force));"));
    // The required-only overload never references the optional parameter.
    const std::size_t first_end = as.find("\t}\n", first);
    EXPECT_EQ(as.substr(first, first_end - first).find("Force"), std::string::npos);
    // Optional scalars of every kind become plain parameters in the full overload.
    EXPECT_TRUE(contains(as, "float Count, FConvexResultDelegate OnResult)"));
    EXPECT_TRUE(contains(as, "FConvexApiSinkKitchenSinkNested Nested, FConvexApiSinkKitchenSinkDelegate OnResult)"));
}

TEST(Emit, ScriptNamesNeverShadowWrapperLocals) {
    // Fields that PascalCase to a wrapper parameter or local get a suffix in
    // every emitter; the script wrapper's own locals start with an underscore.
    const std::string spec = R"([
      {"identifier": "edge.js:get", "functionType": "Query", "visibility": {"kind": "public"},
       "args": {"type": "object", "value": {
         "client": {"fieldType": {"type": "string"}, "optional": false},
         "adapter": {"fieldType": {"type": "string"}, "optional": false},
         "handler": {"fieldType": {"type": "string"}, "optional": false},
         "args": {"fieldType": {"type": "string"}, "optional": false},
         "onResult": {"fieldType": {"type": "string"}, "optional": false}}},
       "returns": {"type": "number"}}
    ])";
    convex_codegen::emit_options opts;
    opts.emit_script = true;
    auto files = convex_codegen::emit_all(spec, opts);
    const std::string& as = files.at("ConvexApi.as");
    EXPECT_TRUE(contains(as, "void Get(UConvexClient Client, FString Adapter, FString Args_2, FString Client_2, FString Handler, FString OnResult_2, FConvexApiEdgeGetDelegate OnResult)"));
    EXPECT_TRUE(contains(as, "UConvexApiEdgeGetAdapter _Adapter = Cast<UConvexApiEdgeGetAdapter>(NewObject(Client, UConvexApiEdgeGetAdapter));"));
    EXPECT_TRUE(contains(as, "_Args.Add(\"client\", Convex::MakeConvexString(Client_2));"));
    EXPECT_TRUE(contains(files.at("ConvexApi.h"), "const FString& Client_2"));
}

TEST(Emit, ScriptStructMembersAreCaseInsensitive) {
    // Reflected struct members are FNames, so `bHasFoo` and a PascalCased
    // `BHasFoo` would collide; the companion gets a suffix.
    const std::string spec = R"([
      {"identifier": "edge.js:shape", "functionType": "Query", "visibility": {"kind": "public"},
       "args": {"type": "object", "value": {}},
       "returns": {"type": "object", "value": {
         "bHasFoo": {"fieldType": {"type": "boolean"}, "optional": false},
         "foo": {"fieldType": {"type": "string"}, "optional": true}}}}
    ])";
    convex_codegen::emit_options opts;
    opts.emit_script = true;
    const std::string as = convex_codegen::emit_all(spec, opts).at("ConvexApi.as");
    EXPECT_TRUE(contains(as, "\tbool BHasFoo = false;\n\tFString Foo;\n\tbool bHasFoo_2 = false;"));
}

TEST(Emit, ScriptPageOfBytesStaysUntyped) {
    // A page of bytes would need TArray<TArray<uint8>>, which the fork
    // rejects, so the paginated wrapper keeps the raw snapshot delegate.
    const std::string spec = R"([
      {"identifier": "edge.js:blobs", "functionType": "Query", "visibility": {"kind": "public"},
       "args": {"type": "object", "value": {
         "paginationOpts": {"fieldType": {"type": "object", "value": {
           "numItems": {"fieldType": {"type": "number"}, "optional": false},
           "cursor": {"fieldType": {"type": "union", "value": [{"type": "string"}, {"type": "null"}]}, "optional": false}}}, "optional": false}}},
       "returns": {"type": "object", "value": {
         "page": {"fieldType": {"type": "array", "value": {"type": "bytes"}}, "optional": false},
         "isDone": {"fieldType": {"type": "boolean"}, "optional": false},
         "continueCursor": {"fieldType": {"type": "string"}, "optional": false}}}}
    ])";
    convex_codegen::emit_options opts;
    opts.emit_script = true;
    const std::string as = convex_codegen::emit_all(spec, opts).at("ConvexApi.as");
    EXPECT_FALSE(contains(as, "TArray<TArray"));
    EXPECT_TRUE(contains(as, "int InitialNumItems, FConvexPaginatedSnapshotDelegate OnUpdate)"));
    EXPECT_TRUE(contains(as, "\tTArray<FConvexValue> Page;\n"));
}

TEST(Emit, IncludeInternalEmitsSecret) {
    convex_codegen::emit_options opts;
    opts.include_internal = true;
    auto files = emit_fixture(opts);
    EXPECT_TRUE(contains(files.at("ConvexApi.h"), "Secret"));
    EXPECT_FALSE(contains(emit_fixture({}).at("ConvexApi.h"), "Secret"));
}
