#include <convex_codegen/emit.h>

#include <gtest/gtest.h>

#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>

namespace fs = std::filesystem;

namespace {

std::string read_text(const fs::path& path) {
    std::ifstream in(path, std::ios::binary);
    std::ostringstream buf;
    buf << in.rdbuf();
    return buf.str();
}

bool contains(const std::string& haystack, const std::string& needle) {
    return haystack.find(needle) != std::string::npos;
}

std::map<std::string, std::string> emit_fixture(const convex_codegen::emit_options& opts) {
    return convex_codegen::emit_all(read_text(FIXTURE_PATH), opts);
}

}  // namespace

TEST(Emit, HeaderProvenance) {
    convex_codegen::emit_options opts;
    opts.stamp = "// STAMP LINE";
    auto files = emit_fixture(opts);
    EXPECT_EQ(files.at("ConvexApi.h").rfind("// Generated by convex-ue-codegen. Do not edit by hand.\n// STAMP LINE\n", 0), 0u);
}

TEST(Emit, SourceLabelWhenNoStamp) {
    convex_codegen::emit_options opts;
    opts.source_label = "https://x.convex.cloud";
    auto files = emit_fixture(opts);
    EXPECT_TRUE(contains(files.at("ConvexApi.h"), "// Source: https://x.convex.cloud\n"));
}

TEST(Emit, NestedNamespaceForSlashModule) {
    auto files = emit_fixture({});
    const std::string& h = files.at("ConvexApi.h");
    EXPECT_TRUE(contains(h, "namespace Admin\n{\nnamespace Tools\n{"));
}

TEST(Emit, QueryGetsWatchVariant) {
    auto files = emit_fixture({});
    const std::string& h = files.at("ConvexApi.h");
    // noArgs is a Query -> both one-shot and Watch wrappers.
    EXPECT_TRUE(contains(h, "void NoArgs(UConvexClient& Client, FConvexResultNative OnResult);"));
    EXPECT_TRUE(contains(h, "UConvexSubscription* WatchNoArgs(UConvexClient& Client, FConvexResultNative OnUpdate);"));
}

TEST(Emit, MutationHasNoWatch) {
    auto files = emit_fixture({});
    const std::string& h = files.at("ConvexApi.h");
    EXPECT_FALSE(contains(h, "WatchReset"));
}

TEST(Emit, PaginatedQueryGetsPaginatedWatchVariant) {
    auto files = emit_fixture({});
    const std::string& h = files.at("ConvexApi.h");
    const std::string& c = files.at("ConvexApi.cpp");
    // messages:listPaginated matches the paginationOpts shape. It keeps its
    // plain X + WatchX wrappers (paginationOpts stays an ordinary arg there)
    // and gains a WatchXPaginated wrapper that drops paginationOpts and takes
    // InitialNumItems + FConvexPaginatedUpdateNativeFn.
    EXPECT_TRUE(contains(h, "void ListPaginated(UConvexClient& Client, const FString& Channel, const FConvexValue& PaginationOpts, FConvexResultNative OnResult);"));
    EXPECT_TRUE(contains(h, "UConvexSubscription* WatchListPaginated(UConvexClient& Client, const FString& Channel, const FConvexValue& PaginationOpts, FConvexResultNative OnUpdate);"));
    EXPECT_TRUE(contains(h, "UConvexPaginatedSubscription* WatchListPaginatedPaginated(UConvexClient& Client, const FString& Channel, int32 InitialNumItems, FConvexPaginatedUpdateNativeFn OnUpdate);"));
    // The paginated impl injects paginationOpts via the client entry point.
    EXPECT_TRUE(contains(c, "return Client.SubscribePaginatedNative(TEXT(\"messages:listPaginated\"), Args, InitialNumItems, MoveTemp(OnUpdate));"));
    // Its Args map must NOT carry paginationOpts (the client injects it).
    const std::size_t pag = c.find("WatchListPaginatedPaginated(UConvexClient& Client");
    ASSERT_NE(pag, std::string::npos);
    const std::size_t body_end = c.find("\n}", pag);
    EXPECT_EQ(c.substr(pag, body_end - pag).find("paginationOpts"), std::string::npos);
}

TEST(Emit, PaginatedIncludesPluginHeader) {
    auto files = emit_fixture({});
    // The header pulls in ConvexPaginatedSubscription.h for the alias/type.
    EXPECT_TRUE(contains(files.at("ConvexApi.h"), "#include \"ConvexPaginatedSubscription.h\""));
}

TEST(Emit, NonMatchingPaginationOptsGetsNoPaginatedVariant) {
    auto files = emit_fixture({});
    const std::string& h = files.at("ConvexApi.h");
    // messages:listBad has a paginationOpts arg missing `cursor`: it is a plain
    // query (X + WatchX) and must NOT get a paginated wrapper.
    EXPECT_TRUE(contains(h, "UConvexSubscription* WatchListBad(UConvexClient& Client, const FString& Channel, const FConvexValue& PaginationOpts, FConvexResultNative OnUpdate);"));
    EXPECT_FALSE(contains(h, "WatchListBadPaginated"));
}

TEST(Emit, PassthroughForAnyArgs) {
    auto files = emit_fixture({});
    const std::string& c = files.at("ConvexApi.cpp");
    // anyArgs (args: any) -> single TMap pass-through, forwarded directly.
    EXPECT_TRUE(contains(c, "void ConvexApi::Sink::AnyArgs(UConvexClient& Client, const TMap<FString, FConvexValue>& Args, FConvexResultNative OnResult)"));
    EXPECT_TRUE(contains(c, "Client.MutationNative(TEXT(\"sink:anyArgs\"), Args, MoveTemp(OnResult));"));
}

TEST(Emit, OptionalArgUsesTOptionalAndGuard) {
    auto files = emit_fixture({});
    const std::string& h = files.at("ConvexApi.h");
    const std::string& c = files.at("ConvexApi.cpp");
    // runAction has an optional 'count' number and a required 'uploadId' id.
    EXPECT_TRUE(contains(h, "const TOptional<double>& Count"));
    EXPECT_TRUE(contains(h, "const FString& /* Id<uploads> */ UploadId"));
    EXPECT_TRUE(contains(c, "if (Count.IsSet())"));
    EXPECT_TRUE(contains(c, "Args.Add(TEXT(\"count\"), FConvexValue::Float(Count.GetValue()));"));
}

TEST(Emit, IdCommentAndActionNative) {
    auto files = emit_fixture({});
    const std::string& c = files.at("ConvexApi.cpp");
    EXPECT_TRUE(contains(c, "Client.ActionNative(TEXT(\"sink:runAction\")"));
    EXPECT_TRUE(contains(c, "Args.Add(TEXT(\"uploadId\"), FConvexValue::String(UploadId));"));
}

TEST(Emit, ScalarArrayLoop) {
    auto files = emit_fixture({});
    const std::string& c = files.at("ConvexApi.cpp");
    EXPECT_TRUE(contains(c, "for (const FString& _Item : Tags)"));
    EXPECT_TRUE(contains(c, "_TagsItems.Add(FConvexValue::String(_Item));"));
    EXPECT_TRUE(contains(c, "Args.Add(TEXT(\"tags\"), FConvexValue::Array(_TagsItems));"));
}

TEST(Emit, BlueprintClassAndCategory) {
    auto files = emit_fixture({});
    const std::string& h = files.at("ConvexApiBP.h");
    EXPECT_TRUE(contains(h, "class UConvexApiSinkLibrary : public UBlueprintFunctionLibrary"));
    EXPECT_TRUE(contains(h, "Category = \"Convex API|sink\""));
    EXPECT_TRUE(contains(h, "DisplayName = \"Convex sink:kitchenSink\""));
    // generated.h must be included.
    EXPECT_TRUE(contains(h, "#include \"ConvexApiBP.generated.h\""));
}

TEST(Emit, BlueprintOmitsOptionalArgs) {
    auto files = emit_fixture({});
    const std::string& h = files.at("ConvexApiBP.h");
    // BP RunAction keeps required uploadId (as FString) but drops optional count.
    EXPECT_TRUE(contains(h, "static void RunAction(UConvexClient* Client, const FString& UploadId, FConvexResultDelegate OnResult);"));
    EXPECT_TRUE(contains(h, "optional args omitted; use the C++ wrapper"));
}

TEST(Emit, BlueprintNullGuard) {
    auto files = emit_fixture({});
    const std::string& c = files.at("ConvexApiBP.cpp");
    EXPECT_TRUE(contains(c, "if (Client == nullptr)"));
    EXPECT_TRUE(contains(c, "DEFINE_LOG_CATEGORY_STATIC(LogConvexApiBP, Log, All);"));
}

TEST(Emit, BlueprintBodyOmitsOptionalArgs) {
    // admin/tools:reset has a single optional 'force' arg. The BP wrapper drops
    // it from the signature, so its body must NOT reference a 'Force' parameter.
    auto files = emit_fixture({});
    const std::string& c = files.at("ConvexApiBP.cpp");
    const std::size_t reset = c.find("UConvexApiAdminToolsLibrary::Reset");
    ASSERT_NE(reset, std::string::npos);
    const std::size_t body_end = c.find("\n}", reset);
    const std::string body = c.substr(reset, body_end - reset);
    EXPECT_EQ(body.find("Force"), std::string::npos) << "BP body references dropped optional arg";
    EXPECT_NE(body.find("Client->Mutation(TEXT(\"admin/tools:reset\"), Args, OnResult);"),
              std::string::npos);
}

TEST(Emit, NameCollisionDeduplicated) {
    // foo_bar:x and fooBar:x collide into namespace/class FooBar; the second
    // (by canonical id sort) becomes X_2 / WatchX_2.
    auto files = emit_fixture({});
    const std::string& h = files.at("ConvexApi.h");
    EXPECT_TRUE(contains(h, "void X(UConvexClient& Client, const FString& A, FConvexResultNative OnResult);"));
    EXPECT_TRUE(contains(h, "void X_2(UConvexClient& Client, const FString& A, FConvexResultNative OnResult);"));
    EXPECT_TRUE(contains(h, "WatchX_2"));
}

TEST(Emit, ModuleScaffolding) {
    convex_codegen::emit_options opts;
    opts.emit_module = "MyConvexApi";
    auto files = emit_fixture(opts);
    ASSERT_TRUE(files.count("MyConvexApi.Build.cs"));
    ASSERT_TRUE(files.count("MyConvexApiModule.cpp"));
    EXPECT_TRUE(contains(files.at("MyConvexApi.Build.cs"), "public class MyConvexApi : ModuleRules"));
    EXPECT_TRUE(contains(files.at("MyConvexApi.Build.cs"), "\"ConvexClient\""));
    EXPECT_TRUE(contains(files.at("MyConvexApi.Build.cs"), "\"ConvexCore\""));
    EXPECT_TRUE(contains(files.at("MyConvexApiModule.cpp"), "IMPLEMENT_MODULE(FDefaultModuleImpl, MyConvexApi);"));
    // Without the flag, only the 4 API files are emitted.
    EXPECT_EQ(emit_fixture({}).size(), 4u);
}

TEST(Emit, IncludeInternalEmitsSecret) {
    convex_codegen::emit_options opts;
    opts.include_internal = true;
    auto files = emit_fixture(opts);
    EXPECT_TRUE(contains(files.at("ConvexApi.h"), "Secret"));
    EXPECT_FALSE(contains(emit_fixture({}).at("ConvexApi.h"), "Secret"));
}
