// Generated by convex-ue-codegen. Do not edit by hand.
// Source: apispec_full.json (golden fixture)

#include "ConvexApi.h"

#include "ConvexClient.h"
#include "ConvexSubscription.h"

void ConvexApi::Admin::Tools::Reset(UConvexClient& Client, const TOptional<bool>& Force, FConvexResultNative OnResult)
{
	TMap<FString, FConvexValue> Args;
	if (Force.IsSet())
	{
		Args.Add(TEXT("force"), FConvexValue::Bool(Force.GetValue()));
	}
	Client.MutationNative(TEXT("admin/tools:reset"), Args, MoveTemp(OnResult));
}

void ConvexApi::Counters::Get(UConvexClient& Client, const FString& Name, FConvexResultNative OnResult)
{
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("name"), FConvexValue::String(Name));
	Client.QueryNative(TEXT("counters:get"), Args, MoveTemp(OnResult));
}

UConvexSubscription* ConvexApi::Counters::WatchGet(UConvexClient& Client, const FString& Name, FConvexResultNative OnUpdate)
{
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("name"), FConvexValue::String(Name));
	return Client.SubscribeNative(TEXT("counters:get"), Args, MoveTemp(OnUpdate));
}

void ConvexApi::FooBar::X(UConvexClient& Client, const FString& A, FConvexResultNative OnResult)
{
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("a"), FConvexValue::String(A));
	Client.QueryNative(TEXT("fooBar:x"), Args, MoveTemp(OnResult));
}

UConvexSubscription* ConvexApi::FooBar::WatchX(UConvexClient& Client, const FString& A, FConvexResultNative OnUpdate)
{
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("a"), FConvexValue::String(A));
	return Client.SubscribeNative(TEXT("fooBar:x"), Args, MoveTemp(OnUpdate));
}

void ConvexApi::FooBar::X_2(UConvexClient& Client, const FString& A, FConvexResultNative OnResult)
{
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("a"), FConvexValue::String(A));
	Client.QueryNative(TEXT("foo_bar:x"), Args, MoveTemp(OnResult));
}

UConvexSubscription* ConvexApi::FooBar::WatchX_2(UConvexClient& Client, const FString& A, FConvexResultNative OnUpdate)
{
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("a"), FConvexValue::String(A));
	return Client.SubscribeNative(TEXT("foo_bar:x"), Args, MoveTemp(OnUpdate));
}

void ConvexApi::Messages::List(UConvexClient& Client, const FString& Channel, FConvexResultNative OnResult)
{
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("channel"), FConvexValue::String(Channel));
	Client.QueryNative(TEXT("messages:list"), Args, MoveTemp(OnResult));
}

UConvexSubscription* ConvexApi::Messages::WatchList(UConvexClient& Client, const FString& Channel, FConvexResultNative OnUpdate)
{
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("channel"), FConvexValue::String(Channel));
	return Client.SubscribeNative(TEXT("messages:list"), Args, MoveTemp(OnUpdate));
}

void ConvexApi::Messages::ListBad(UConvexClient& Client, const FString& Channel, const FConvexValue& PaginationOpts, FConvexResultNative OnResult)
{
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("channel"), FConvexValue::String(Channel));
	Args.Add(TEXT("paginationOpts"), PaginationOpts);
	Client.QueryNative(TEXT("messages:listBad"), Args, MoveTemp(OnResult));
}

UConvexSubscription* ConvexApi::Messages::WatchListBad(UConvexClient& Client, const FString& Channel, const FConvexValue& PaginationOpts, FConvexResultNative OnUpdate)
{
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("channel"), FConvexValue::String(Channel));
	Args.Add(TEXT("paginationOpts"), PaginationOpts);
	return Client.SubscribeNative(TEXT("messages:listBad"), Args, MoveTemp(OnUpdate));
}

void ConvexApi::Messages::ListPaginated(UConvexClient& Client, const FString& Channel, const FConvexValue& PaginationOpts, FConvexResultNative OnResult)
{
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("channel"), FConvexValue::String(Channel));
	Args.Add(TEXT("paginationOpts"), PaginationOpts);
	Client.QueryNative(TEXT("messages:listPaginated"), Args, MoveTemp(OnResult));
}

UConvexSubscription* ConvexApi::Messages::WatchListPaginated(UConvexClient& Client, const FString& Channel, const FConvexValue& PaginationOpts, FConvexResultNative OnUpdate)
{
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("channel"), FConvexValue::String(Channel));
	Args.Add(TEXT("paginationOpts"), PaginationOpts);
	return Client.SubscribeNative(TEXT("messages:listPaginated"), Args, MoveTemp(OnUpdate));
}

UConvexPaginatedSubscription* ConvexApi::Messages::WatchListPaginatedPaginated(UConvexClient& Client, const FString& Channel, int32 InitialNumItems, FConvexPaginatedUpdateNativeFn OnUpdate)
{
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("channel"), FConvexValue::String(Channel));
	return Client.SubscribePaginatedNative(TEXT("messages:listPaginated"), Args, InitialNumItems, MoveTemp(OnUpdate));
}

void ConvexApi::Sink::AnyArgs(UConvexClient& Client, const TMap<FString, FConvexValue>& Args, FConvexResultNative OnResult)
{
	Client.MutationNative(TEXT("sink:anyArgs"), Args, MoveTemp(OnResult));
}

void ConvexApi::Sink::KitchenSink(UConvexClient& Client, const FConvexValue& AnyField, bool B, int64 Big, const TArray<uint8>& By, const TArray<int64>& Counts, const FString& /* Id<documents> */ DocId, double F, const TArray<bool>& Flags, int64 I, const TArray<FConvexValue>& Items, bool LitBool, double LitNum, const FString& LitStr, double N, const FConvexValue& Nul, const TArray<double>& Nums, const FConvexValue& Rec, const FString& S, const TArray<FString>& Tags, const FConvexValue& Uni, const TOptional<FConvexValue>& Nested, FConvexResultNative OnResult)
{
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("anyField"), AnyField);
	Args.Add(TEXT("b"), FConvexValue::Bool(B));
	Args.Add(TEXT("big"), FConvexValue::Int64(Big));
	Args.Add(TEXT("by"), FConvexValue::Bytes(By));
	{
		TArray<FConvexValue> _CountsItems;
		for (const int64& _Item : Counts)
		{
			_CountsItems.Add(FConvexValue::Int64(_Item));
		}
		Args.Add(TEXT("counts"), FConvexValue::Array(_CountsItems));
	}
	Args.Add(TEXT("docId"), FConvexValue::String(DocId));
	Args.Add(TEXT("f"), FConvexValue::Float(F));
	{
		TArray<FConvexValue> _FlagsItems;
		for (const bool& _Item : Flags)
		{
			_FlagsItems.Add(FConvexValue::Bool(_Item));
		}
		Args.Add(TEXT("flags"), FConvexValue::Array(_FlagsItems));
	}
	Args.Add(TEXT("i"), FConvexValue::Int64(I));
	Args.Add(TEXT("items"), FConvexValue::Array(Items));
	Args.Add(TEXT("litBool"), FConvexValue::Bool(LitBool));
	Args.Add(TEXT("litNum"), FConvexValue::Float(LitNum));
	Args.Add(TEXT("litStr"), FConvexValue::String(LitStr));
	Args.Add(TEXT("n"), FConvexValue::Float(N));
	Args.Add(TEXT("nul"), Nul);
	{
		TArray<FConvexValue> _NumsItems;
		for (const double& _Item : Nums)
		{
			_NumsItems.Add(FConvexValue::Float(_Item));
		}
		Args.Add(TEXT("nums"), FConvexValue::Array(_NumsItems));
	}
	Args.Add(TEXT("rec"), Rec);
	Args.Add(TEXT("s"), FConvexValue::String(S));
	{
		TArray<FConvexValue> _TagsItems;
		for (const FString& _Item : Tags)
		{
			_TagsItems.Add(FConvexValue::String(_Item));
		}
		Args.Add(TEXT("tags"), FConvexValue::Array(_TagsItems));
	}
	Args.Add(TEXT("uni"), Uni);
	if (Nested.IsSet())
	{
		Args.Add(TEXT("nested"), Nested.GetValue());
	}
	Client.QueryNative(TEXT("sink:kitchenSink"), Args, MoveTemp(OnResult));
}

UConvexSubscription* ConvexApi::Sink::WatchKitchenSink(UConvexClient& Client, const FConvexValue& AnyField, bool B, int64 Big, const TArray<uint8>& By, const TArray<int64>& Counts, const FString& /* Id<documents> */ DocId, double F, const TArray<bool>& Flags, int64 I, const TArray<FConvexValue>& Items, bool LitBool, double LitNum, const FString& LitStr, double N, const FConvexValue& Nul, const TArray<double>& Nums, const FConvexValue& Rec, const FString& S, const TArray<FString>& Tags, const FConvexValue& Uni, const TOptional<FConvexValue>& Nested, FConvexResultNative OnUpdate)
{
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("anyField"), AnyField);
	Args.Add(TEXT("b"), FConvexValue::Bool(B));
	Args.Add(TEXT("big"), FConvexValue::Int64(Big));
	Args.Add(TEXT("by"), FConvexValue::Bytes(By));
	{
		TArray<FConvexValue> _CountsItems;
		for (const int64& _Item : Counts)
		{
			_CountsItems.Add(FConvexValue::Int64(_Item));
		}
		Args.Add(TEXT("counts"), FConvexValue::Array(_CountsItems));
	}
	Args.Add(TEXT("docId"), FConvexValue::String(DocId));
	Args.Add(TEXT("f"), FConvexValue::Float(F));
	{
		TArray<FConvexValue> _FlagsItems;
		for (const bool& _Item : Flags)
		{
			_FlagsItems.Add(FConvexValue::Bool(_Item));
		}
		Args.Add(TEXT("flags"), FConvexValue::Array(_FlagsItems));
	}
	Args.Add(TEXT("i"), FConvexValue::Int64(I));
	Args.Add(TEXT("items"), FConvexValue::Array(Items));
	Args.Add(TEXT("litBool"), FConvexValue::Bool(LitBool));
	Args.Add(TEXT("litNum"), FConvexValue::Float(LitNum));
	Args.Add(TEXT("litStr"), FConvexValue::String(LitStr));
	Args.Add(TEXT("n"), FConvexValue::Float(N));
	Args.Add(TEXT("nul"), Nul);
	{
		TArray<FConvexValue> _NumsItems;
		for (const double& _Item : Nums)
		{
			_NumsItems.Add(FConvexValue::Float(_Item));
		}
		Args.Add(TEXT("nums"), FConvexValue::Array(_NumsItems));
	}
	Args.Add(TEXT("rec"), Rec);
	Args.Add(TEXT("s"), FConvexValue::String(S));
	{
		TArray<FConvexValue> _TagsItems;
		for (const FString& _Item : Tags)
		{
			_TagsItems.Add(FConvexValue::String(_Item));
		}
		Args.Add(TEXT("tags"), FConvexValue::Array(_TagsItems));
	}
	Args.Add(TEXT("uni"), Uni);
	if (Nested.IsSet())
	{
		Args.Add(TEXT("nested"), Nested.GetValue());
	}
	return Client.SubscribeNative(TEXT("sink:kitchenSink"), Args, MoveTemp(OnUpdate));
}

void ConvexApi::Sink::NoArgs(UConvexClient& Client, FConvexResultNative OnResult)
{
	TMap<FString, FConvexValue> Args;
	Client.QueryNative(TEXT("sink:noArgs"), Args, MoveTemp(OnResult));
}

UConvexSubscription* ConvexApi::Sink::WatchNoArgs(UConvexClient& Client, FConvexResultNative OnUpdate)
{
	TMap<FString, FConvexValue> Args;
	return Client.SubscribeNative(TEXT("sink:noArgs"), Args, MoveTemp(OnUpdate));
}

void ConvexApi::Sink::RunAction(UConvexClient& Client, const FString& /* Id<uploads> */ UploadId, const TOptional<double>& Count, FConvexResultNative OnResult)
{
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("uploadId"), FConvexValue::String(UploadId));
	if (Count.IsSet())
	{
		Args.Add(TEXT("count"), FConvexValue::Float(Count.GetValue()));
	}
	Client.ActionNative(TEXT("sink:runAction"), Args, MoveTemp(OnResult));
}

