// Generated by convex-ue-codegen. Do not edit by hand.
// Source: apispec_full.json (golden fixture)

// Typed AngelScript wrappers for the deployed Convex functions, for the
// Hazelight UnrealEngine-Angelscript fork. Put this file under the project's
// Script/ folder; it needs no build step and hot-reloads. Requires the Convex
// plugin. Functions with optional arguments have two overloads: required
// arguments only, and every argument. Named arguments work: Fn(Client,
// Name = "hits", By = 2.0, OnResult = Handler).

namespace ConvexApi::Admin::Tools
{
	/// admin/tools.js:reset (Mutation)
	/// args:    object{ force?: boolean }
	/// returns: any
	void Reset(UConvexClient Client, FConvexResultDelegate OnResult)
	{
		TMap<FString, FConvexValue> Args;
		Client.Mutation("admin/tools:reset", Args, OnResult);
	}

	/// All arguments, including the optional ones.
	void Reset(UConvexClient Client, bool Force, FConvexResultDelegate OnResult)
	{
		TMap<FString, FConvexValue> Args;
		Args.Add("force", Convex::MakeConvexBool(Force));
		Client.Mutation("admin/tools:reset", Args, OnResult);
	}
}

namespace ConvexApi::FooBar
{
	/// fooBar.js:x (Query)
	/// args:    object{ a: string }
	/// returns: any
	void X(UConvexClient Client, FString A, FConvexResultDelegate OnResult)
	{
		TMap<FString, FConvexValue> Args;
		Args.Add("a", Convex::MakeConvexString(A));
		Client.Query("fooBar:x", Args, OnResult);
	}

	UConvexSubscription WatchX(UConvexClient Client, FString A, FConvexResultDelegate OnUpdate)
	{
		TMap<FString, FConvexValue> Args;
		Args.Add("a", Convex::MakeConvexString(A));
		return Client.Subscribe("fooBar:x", Args, OnUpdate);
	}

	/// foo_bar.js:x (Query)
	/// args:    object{ a: string }
	/// returns: any
	void X_2(UConvexClient Client, FString A, FConvexResultDelegate OnResult)
	{
		TMap<FString, FConvexValue> Args;
		Args.Add("a", Convex::MakeConvexString(A));
		Client.Query("foo_bar:x", Args, OnResult);
	}

	UConvexSubscription WatchX_2(UConvexClient Client, FString A, FConvexResultDelegate OnUpdate)
	{
		TMap<FString, FConvexValue> Args;
		Args.Add("a", Convex::MakeConvexString(A));
		return Client.Subscribe("foo_bar:x", Args, OnUpdate);
	}
}

namespace ConvexApi::Messages
{
	/// messages.js:listBad (Query)
	/// args:    object{ channel: string, paginationOpts: object{ numItems: number } }
	/// returns: any
	void ListBad(UConvexClient Client, FString Channel, FConvexValue PaginationOpts, FConvexResultDelegate OnResult)
	{
		TMap<FString, FConvexValue> Args;
		Args.Add("channel", Convex::MakeConvexString(Channel));
		Args.Add("paginationOpts", PaginationOpts);
		Client.Query("messages:listBad", Args, OnResult);
	}

	UConvexSubscription WatchListBad(UConvexClient Client, FString Channel, FConvexValue PaginationOpts, FConvexResultDelegate OnUpdate)
	{
		TMap<FString, FConvexValue> Args;
		Args.Add("channel", Convex::MakeConvexString(Channel));
		Args.Add("paginationOpts", PaginationOpts);
		return Client.Subscribe("messages:listBad", Args, OnUpdate);
	}

	/// messages.js:listPaginated (Query)
	/// args:    object{ channel: string, paginationOpts: object{ cursor: union<string | null>, endCursor?: union<string | null>, id?: number, maximumBytesRead?: number, maximumRowsRead?: number, numItems: number } }
	/// returns: any
	void ListPaginated(UConvexClient Client, FString Channel, FConvexValue PaginationOpts, FConvexResultDelegate OnResult)
	{
		TMap<FString, FConvexValue> Args;
		Args.Add("channel", Convex::MakeConvexString(Channel));
		Args.Add("paginationOpts", PaginationOpts);
		Client.Query("messages:listPaginated", Args, OnResult);
	}

	UConvexSubscription WatchListPaginated(UConvexClient Client, FString Channel, FConvexValue PaginationOpts, FConvexResultDelegate OnUpdate)
	{
		TMap<FString, FConvexValue> Args;
		Args.Add("channel", Convex::MakeConvexString(Channel));
		Args.Add("paginationOpts", PaginationOpts);
		return Client.Subscribe("messages:listPaginated", Args, OnUpdate);
	}

	/// Subscribes messages:listPaginated as a growing live list (the usePaginatedQuery
	/// pattern); paginationOpts is injected by the client.
	UConvexPaginatedSubscription WatchListPaginatedPaginated(UConvexClient Client, FString Channel, int InitialNumItems, FConvexPaginatedSnapshotDelegate OnUpdate)
	{
		TMap<FString, FConvexValue> Args;
		Args.Add("channel", Convex::MakeConvexString(Channel));
		return Client.SubscribePaginated("messages:listPaginated", Args, InitialNumItems, OnUpdate);
	}
}

namespace ConvexApi::Sink
{
	/// sink.js:anyArgs (Mutation)
	/// args:    any
	/// returns: any
	void AnyArgs(UConvexClient Client, TMap<FString, FConvexValue> Args, FConvexResultDelegate OnResult)
	{
		Client.Mutation("sink:anyArgs", Args, OnResult);
	}

	/// sink.js:kitchenSink (Query)
	/// args:    object{ anyField: any, b: boolean, big: bigint, by: bytes, counts: array<int64>, docId: id<documents>, f: float64, flags: array<boolean>, i: int64, items: array<object{ id: string, qty: int64 }>, litBool: literal(true), litNum: literal(42), litStr: literal("hello"), n: number, nested?: object{ deep?: object{ x: number }, inner: string }, nul: null, nums: array<number>, rec: record<string, number>, s: string, tags: array<string>, uni: union<string | number | object{ k: boolean }> }
	/// returns: object{ ok: boolean }
	void KitchenSink(UConvexClient Client, FConvexValue AnyField, bool B, int64 Big, TArray<uint8> By, TArray<int64> Counts, FString DocId, float F, TArray<bool> Flags, int64 I, TArray<FConvexValue> Items, bool LitBool, float LitNum, FString LitStr, float N, FConvexValue Nul, TArray<float> Nums, FConvexValue Rec, FString S, TArray<FString> Tags, FConvexValue Uni, FConvexResultDelegate OnResult)
	{
		TMap<FString, FConvexValue> Args;
		Args.Add("anyField", AnyField);
		Args.Add("b", Convex::MakeConvexBool(B));
		Args.Add("big", Convex::MakeConvexInt(Big));
		Args.Add("by", Convex::MakeConvexBytes(By));
		{
			TArray<FConvexValue> _CountsItems;
			for (const int64& _Item : Counts)
			{
				_CountsItems.Add(Convex::MakeConvexInt(_Item));
			}
			Args.Add("counts", Convex::MakeConvexArray(_CountsItems));
		}
		Args.Add("docId", Convex::MakeConvexString(DocId));
		Args.Add("f", Convex::MakeConvexFloat(F));
		{
			TArray<FConvexValue> _FlagsItems;
			for (const bool& _Item : Flags)
			{
				_FlagsItems.Add(Convex::MakeConvexBool(_Item));
			}
			Args.Add("flags", Convex::MakeConvexArray(_FlagsItems));
		}
		Args.Add("i", Convex::MakeConvexInt(I));
		Args.Add("items", Convex::MakeConvexArray(Items));
		Args.Add("litBool", Convex::MakeConvexBool(LitBool));
		Args.Add("litNum", Convex::MakeConvexFloat(LitNum));
		Args.Add("litStr", Convex::MakeConvexString(LitStr));
		Args.Add("n", Convex::MakeConvexFloat(N));
		Args.Add("nul", Nul);
		{
			TArray<FConvexValue> _NumsItems;
			for (const float& _Item : Nums)
			{
				_NumsItems.Add(Convex::MakeConvexFloat(_Item));
			}
			Args.Add("nums", Convex::MakeConvexArray(_NumsItems));
		}
		Args.Add("rec", Rec);
		Args.Add("s", Convex::MakeConvexString(S));
		{
			TArray<FConvexValue> _TagsItems;
			for (const FString& _Item : Tags)
			{
				_TagsItems.Add(Convex::MakeConvexString(_Item));
			}
			Args.Add("tags", Convex::MakeConvexArray(_TagsItems));
		}
		Args.Add("uni", Uni);
		Client.Query("sink:kitchenSink", Args, OnResult);
	}

	/// All arguments, including the optional ones.
	void KitchenSink(UConvexClient Client, FConvexValue AnyField, bool B, int64 Big, TArray<uint8> By, TArray<int64> Counts, FString DocId, float F, TArray<bool> Flags, int64 I, TArray<FConvexValue> Items, bool LitBool, float LitNum, FString LitStr, float N, FConvexValue Nul, TArray<float> Nums, FConvexValue Rec, FString S, TArray<FString> Tags, FConvexValue Uni, FConvexValue Nested, FConvexResultDelegate OnResult)
	{
		TMap<FString, FConvexValue> Args;
		Args.Add("anyField", AnyField);
		Args.Add("b", Convex::MakeConvexBool(B));
		Args.Add("big", Convex::MakeConvexInt(Big));
		Args.Add("by", Convex::MakeConvexBytes(By));
		{
			TArray<FConvexValue> _CountsItems;
			for (const int64& _Item : Counts)
			{
				_CountsItems.Add(Convex::MakeConvexInt(_Item));
			}
			Args.Add("counts", Convex::MakeConvexArray(_CountsItems));
		}
		Args.Add("docId", Convex::MakeConvexString(DocId));
		Args.Add("f", Convex::MakeConvexFloat(F));
		{
			TArray<FConvexValue> _FlagsItems;
			for (const bool& _Item : Flags)
			{
				_FlagsItems.Add(Convex::MakeConvexBool(_Item));
			}
			Args.Add("flags", Convex::MakeConvexArray(_FlagsItems));
		}
		Args.Add("i", Convex::MakeConvexInt(I));
		Args.Add("items", Convex::MakeConvexArray(Items));
		Args.Add("litBool", Convex::MakeConvexBool(LitBool));
		Args.Add("litNum", Convex::MakeConvexFloat(LitNum));
		Args.Add("litStr", Convex::MakeConvexString(LitStr));
		Args.Add("n", Convex::MakeConvexFloat(N));
		Args.Add("nul", Nul);
		{
			TArray<FConvexValue> _NumsItems;
			for (const float& _Item : Nums)
			{
				_NumsItems.Add(Convex::MakeConvexFloat(_Item));
			}
			Args.Add("nums", Convex::MakeConvexArray(_NumsItems));
		}
		Args.Add("rec", Rec);
		Args.Add("s", Convex::MakeConvexString(S));
		{
			TArray<FConvexValue> _TagsItems;
			for (const FString& _Item : Tags)
			{
				_TagsItems.Add(Convex::MakeConvexString(_Item));
			}
			Args.Add("tags", Convex::MakeConvexArray(_TagsItems));
		}
		Args.Add("uni", Uni);
		Args.Add("nested", Nested);
		Client.Query("sink:kitchenSink", Args, OnResult);
	}

	UConvexSubscription WatchKitchenSink(UConvexClient Client, FConvexValue AnyField, bool B, int64 Big, TArray<uint8> By, TArray<int64> Counts, FString DocId, float F, TArray<bool> Flags, int64 I, TArray<FConvexValue> Items, bool LitBool, float LitNum, FString LitStr, float N, FConvexValue Nul, TArray<float> Nums, FConvexValue Rec, FString S, TArray<FString> Tags, FConvexValue Uni, FConvexResultDelegate OnUpdate)
	{
		TMap<FString, FConvexValue> Args;
		Args.Add("anyField", AnyField);
		Args.Add("b", Convex::MakeConvexBool(B));
		Args.Add("big", Convex::MakeConvexInt(Big));
		Args.Add("by", Convex::MakeConvexBytes(By));
		{
			TArray<FConvexValue> _CountsItems;
			for (const int64& _Item : Counts)
			{
				_CountsItems.Add(Convex::MakeConvexInt(_Item));
			}
			Args.Add("counts", Convex::MakeConvexArray(_CountsItems));
		}
		Args.Add("docId", Convex::MakeConvexString(DocId));
		Args.Add("f", Convex::MakeConvexFloat(F));
		{
			TArray<FConvexValue> _FlagsItems;
			for (const bool& _Item : Flags)
			{
				_FlagsItems.Add(Convex::MakeConvexBool(_Item));
			}
			Args.Add("flags", Convex::MakeConvexArray(_FlagsItems));
		}
		Args.Add("i", Convex::MakeConvexInt(I));
		Args.Add("items", Convex::MakeConvexArray(Items));
		Args.Add("litBool", Convex::MakeConvexBool(LitBool));
		Args.Add("litNum", Convex::MakeConvexFloat(LitNum));
		Args.Add("litStr", Convex::MakeConvexString(LitStr));
		Args.Add("n", Convex::MakeConvexFloat(N));
		Args.Add("nul", Nul);
		{
			TArray<FConvexValue> _NumsItems;
			for (const float& _Item : Nums)
			{
				_NumsItems.Add(Convex::MakeConvexFloat(_Item));
			}
			Args.Add("nums", Convex::MakeConvexArray(_NumsItems));
		}
		Args.Add("rec", Rec);
		Args.Add("s", Convex::MakeConvexString(S));
		{
			TArray<FConvexValue> _TagsItems;
			for (const FString& _Item : Tags)
			{
				_TagsItems.Add(Convex::MakeConvexString(_Item));
			}
			Args.Add("tags", Convex::MakeConvexArray(_TagsItems));
		}
		Args.Add("uni", Uni);
		return Client.Subscribe("sink:kitchenSink", Args, OnUpdate);
	}

	/// All arguments, including the optional ones.
	UConvexSubscription WatchKitchenSink(UConvexClient Client, FConvexValue AnyField, bool B, int64 Big, TArray<uint8> By, TArray<int64> Counts, FString DocId, float F, TArray<bool> Flags, int64 I, TArray<FConvexValue> Items, bool LitBool, float LitNum, FString LitStr, float N, FConvexValue Nul, TArray<float> Nums, FConvexValue Rec, FString S, TArray<FString> Tags, FConvexValue Uni, FConvexValue Nested, FConvexResultDelegate OnUpdate)
	{
		TMap<FString, FConvexValue> Args;
		Args.Add("anyField", AnyField);
		Args.Add("b", Convex::MakeConvexBool(B));
		Args.Add("big", Convex::MakeConvexInt(Big));
		Args.Add("by", Convex::MakeConvexBytes(By));
		{
			TArray<FConvexValue> _CountsItems;
			for (const int64& _Item : Counts)
			{
				_CountsItems.Add(Convex::MakeConvexInt(_Item));
			}
			Args.Add("counts", Convex::MakeConvexArray(_CountsItems));
		}
		Args.Add("docId", Convex::MakeConvexString(DocId));
		Args.Add("f", Convex::MakeConvexFloat(F));
		{
			TArray<FConvexValue> _FlagsItems;
			for (const bool& _Item : Flags)
			{
				_FlagsItems.Add(Convex::MakeConvexBool(_Item));
			}
			Args.Add("flags", Convex::MakeConvexArray(_FlagsItems));
		}
		Args.Add("i", Convex::MakeConvexInt(I));
		Args.Add("items", Convex::MakeConvexArray(Items));
		Args.Add("litBool", Convex::MakeConvexBool(LitBool));
		Args.Add("litNum", Convex::MakeConvexFloat(LitNum));
		Args.Add("litStr", Convex::MakeConvexString(LitStr));
		Args.Add("n", Convex::MakeConvexFloat(N));
		Args.Add("nul", Nul);
		{
			TArray<FConvexValue> _NumsItems;
			for (const float& _Item : Nums)
			{
				_NumsItems.Add(Convex::MakeConvexFloat(_Item));
			}
			Args.Add("nums", Convex::MakeConvexArray(_NumsItems));
		}
		Args.Add("rec", Rec);
		Args.Add("s", Convex::MakeConvexString(S));
		{
			TArray<FConvexValue> _TagsItems;
			for (const FString& _Item : Tags)
			{
				_TagsItems.Add(Convex::MakeConvexString(_Item));
			}
			Args.Add("tags", Convex::MakeConvexArray(_TagsItems));
		}
		Args.Add("uni", Uni);
		Args.Add("nested", Nested);
		return Client.Subscribe("sink:kitchenSink", Args, OnUpdate);
	}

	/// sink.js:noArgs (Query)
	/// args:    object{ }
	/// returns: any
	void NoArgs(UConvexClient Client, FConvexResultDelegate OnResult)
	{
		TMap<FString, FConvexValue> Args;
		Client.Query("sink:noArgs", Args, OnResult);
	}

	UConvexSubscription WatchNoArgs(UConvexClient Client, FConvexResultDelegate OnUpdate)
	{
		TMap<FString, FConvexValue> Args;
		return Client.Subscribe("sink:noArgs", Args, OnUpdate);
	}

	/// sink.js:runAction (Action)
	/// args:    object{ count?: number, uploadId: id<uploads> }
	/// returns: any
	void RunAction(UConvexClient Client, FString UploadId, FConvexResultDelegate OnResult)
	{
		TMap<FString, FConvexValue> Args;
		Args.Add("uploadId", Convex::MakeConvexString(UploadId));
		Client.Action("sink:runAction", Args, OnResult);
	}

	/// All arguments, including the optional ones.
	void RunAction(UConvexClient Client, FString UploadId, float Count, FConvexResultDelegate OnResult)
	{
		TMap<FString, FConvexValue> Args;
		Args.Add("uploadId", Convex::MakeConvexString(UploadId));
		Args.Add("count", Convex::MakeConvexFloat(Count));
		Client.Action("sink:runAction", Args, OnResult);
	}
}

