// Generated by convex-ue-codegen. Do not edit by hand.
// Source: apispec_full.json (golden fixture)

#pragma once

// Typed native C++ wrappers for the deployed Convex functions.
// Compiles inside a UE module (depends on the ConvexClient module).

#include "CoreMinimal.h"
#include "ConvexValue.h"
#include "ConvexDelegates.h"
#include "ConvexPaginatedSubscription.h"

class UConvexClient;
class UConvexSubscription;

namespace ConvexApi
{

namespace Admin
{
namespace Tools
{

	/// admin/tools.js:reset (Mutation)
	/// args:    object{ force?: boolean }
	/// returns: any
	void Reset(UConvexClient& Client, const TOptional<bool>& Force, FConvexResultNative OnResult);

}  // namespace Tools
}  // namespace Admin

namespace Counters
{

	/// counters.js:get (Query)
	/// args:    object{ name: string }
	/// returns: number
	void Get(UConvexClient& Client, const FString& Name, FConvexResultNative OnResult);
	UConvexSubscription* WatchGet(UConvexClient& Client, const FString& Name, FConvexResultNative OnUpdate);

}  // namespace Counters

namespace FooBar
{

	/// fooBar.js:x (Query)
	/// args:    object{ a: string }
	/// returns: any
	void X(UConvexClient& Client, const FString& A, FConvexResultNative OnResult);
	UConvexSubscription* WatchX(UConvexClient& Client, const FString& A, FConvexResultNative OnUpdate);

	/// foo_bar.js:x (Query)
	/// args:    object{ a: string }
	/// returns: any
	void X_2(UConvexClient& Client, const FString& A, FConvexResultNative OnResult);
	UConvexSubscription* WatchX_2(UConvexClient& Client, const FString& A, FConvexResultNative OnUpdate);

}  // namespace FooBar

namespace Messages
{

	/// messages.js:list (Query)
	/// args:    object{ channel: string }
	/// returns: array<object{ _creationTime: number, _id: id<messages>, author: string, body: string, channel: string, edited?: boolean }>
	void List(UConvexClient& Client, const FString& Channel, FConvexResultNative OnResult);
	UConvexSubscription* WatchList(UConvexClient& Client, const FString& Channel, FConvexResultNative OnUpdate);

	/// messages.js:listBad (Query)
	/// args:    object{ channel: string, paginationOpts: object{ numItems: number } }
	/// returns: any
	void ListBad(UConvexClient& Client, const FString& Channel, const FConvexValue& PaginationOpts, FConvexResultNative OnResult);
	UConvexSubscription* WatchListBad(UConvexClient& Client, const FString& Channel, const FConvexValue& PaginationOpts, FConvexResultNative OnUpdate);

	/// messages.js:listPaginated (Query)
	/// args:    object{ channel: string, paginationOpts: object{ cursor: union<string | null>, endCursor?: union<string | null>, id?: number, maximumBytesRead?: number, maximumRowsRead?: number, numItems: number } }
	/// returns: object{ continueCursor: string, isDone: boolean, page: array<object{ _creationTime: number, _id: id<messages>, author: string, body: string, channel: string, edited?: boolean }> }
	void ListPaginated(UConvexClient& Client, const FString& Channel, const FConvexValue& PaginationOpts, FConvexResultNative OnResult);
	UConvexSubscription* WatchListPaginated(UConvexClient& Client, const FString& Channel, const FConvexValue& PaginationOpts, FConvexResultNative OnUpdate);
	/// Subscribes messages:listPaginated as a growing live list (the usePaginatedQuery
	/// pattern); paginationOpts is injected by the client.
	UConvexPaginatedSubscription* WatchListPaginatedPaginated(UConvexClient& Client, const FString& Channel, int32 InitialNumItems, FConvexPaginatedUpdateNativeFn OnUpdate);

}  // namespace Messages

namespace Sink
{

	/// sink.js:anyArgs (Mutation)
	/// args:    any
	/// returns: any
	void AnyArgs(UConvexClient& Client, const TMap<FString, FConvexValue>& Args, FConvexResultNative OnResult);

	/// sink.js:kitchenSink (Query)
	/// args:    object{ anyField: any, b: boolean, big: bigint, by: bytes, counts: array<int64>, docId: id<documents>, f: float64, flags: array<boolean>, i: int64, items: array<object{ id: string, qty: int64 }>, litBool: literal(true), litNum: literal(42), litStr: literal("hello"), n: number, nested?: object{ deep?: object{ x: number }, inner: string }, nul: null, nums: array<number>, rec: record<string, number>, s: string, tags: array<string>, uni: union<string | number | object{ k: boolean }> }
	/// returns: object{ ok: boolean }
	void KitchenSink(UConvexClient& Client, const FConvexValue& AnyField, bool B, int64 Big, const TArray<uint8>& By, const TArray<int64>& Counts, const FString& /* Id<documents> */ DocId, double F, const TArray<bool>& Flags, int64 I, const TArray<FConvexValue>& Items, bool LitBool, double LitNum, const FString& LitStr, double N, const FConvexValue& Nul, const TArray<double>& Nums, const FConvexValue& Rec, const FString& S, const TArray<FString>& Tags, const FConvexValue& Uni, const TOptional<FConvexValue>& Nested, FConvexResultNative OnResult);
	UConvexSubscription* WatchKitchenSink(UConvexClient& Client, const FConvexValue& AnyField, bool B, int64 Big, const TArray<uint8>& By, const TArray<int64>& Counts, const FString& /* Id<documents> */ DocId, double F, const TArray<bool>& Flags, int64 I, const TArray<FConvexValue>& Items, bool LitBool, double LitNum, const FString& LitStr, double N, const FConvexValue& Nul, const TArray<double>& Nums, const FConvexValue& Rec, const FString& S, const TArray<FString>& Tags, const FConvexValue& Uni, const TOptional<FConvexValue>& Nested, FConvexResultNative OnUpdate);

	/// sink.js:noArgs (Query)
	/// args:    object{ }
	/// returns: any
	void NoArgs(UConvexClient& Client, FConvexResultNative OnResult);
	UConvexSubscription* WatchNoArgs(UConvexClient& Client, FConvexResultNative OnUpdate);

	/// sink.js:runAction (Action)
	/// args:    object{ count?: number, uploadId: id<uploads> }
	/// returns: any
	void RunAction(UConvexClient& Client, const FString& /* Id<uploads> */ UploadId, const TOptional<double>& Count, FConvexResultNative OnResult);

}  // namespace Sink

}  // namespace ConvexApi
