// Generated by convex-ue-codegen. Do not edit by hand.
// Source: apispec_full.json (golden fixture)

#pragma once

// Typed native C++ wrappers for the deployed Convex functions.
// Compiles inside a UE module (depends on the ConvexClient module).

#include "CoreMinimal.h"
#include "ConvexValue.h"
#include "ConvexDelegates.h"

class UConvexClient;
class UConvexSubscription;

namespace ConvexApi
{

namespace Admin
{
namespace Tools
{

	/// admin/tools.js:reset (Mutation)
	/// args:    object{ force?: boolean }
	/// returns: any
	void Reset(UConvexClient& Client, const TOptional<bool>& Force, FConvexResultNative OnResult);

}  // namespace Tools
}  // namespace Admin

namespace FooBar
{

	/// fooBar.js:x (Query)
	/// args:    object{ a: string }
	/// returns: any
	void X(UConvexClient& Client, const FString& A, FConvexResultNative OnResult);
	UConvexSubscription* WatchX(UConvexClient& Client, const FString& A, FConvexResultNative OnUpdate);

	/// foo_bar.js:x (Query)
	/// args:    object{ a: string }
	/// returns: any
	void X_2(UConvexClient& Client, const FString& A, FConvexResultNative OnResult);
	UConvexSubscription* WatchX_2(UConvexClient& Client, const FString& A, FConvexResultNative OnUpdate);

}  // namespace FooBar

namespace Sink
{

	/// sink.js:anyArgs (Mutation)
	/// args:    any
	/// returns: any
	void AnyArgs(UConvexClient& Client, const TMap<FString, FConvexValue>& Args, FConvexResultNative OnResult);

	/// sink.js:kitchenSink (Query)
	/// args:    object{ anyField: any, b: boolean, big: bigint, by: bytes, counts: array<int64>, docId: id<documents>, f: float64, flags: array<boolean>, i: int64, items: array<object{ id: string, qty: int64 }>, litBool: literal(true), litNum: literal(42), litStr: literal("hello"), n: number, nested?: object{ deep?: object{ x: number }, inner: string }, nul: null, nums: array<number>, rec: record<string, number>, s: string, tags: array<string>, uni: union<string | number | object{ k: boolean }> }
	/// returns: object{ ok: boolean }
	void KitchenSink(UConvexClient& Client, const FConvexValue& AnyField, bool B, int64 Big, const TArray<uint8>& By, const TArray<int64>& Counts, const FString& /* Id<documents> */ DocId, double F, const TArray<bool>& Flags, int64 I, const TArray<FConvexValue>& Items, bool LitBool, double LitNum, const FString& LitStr, double N, const FConvexValue& Nul, const TArray<double>& Nums, const FConvexValue& Rec, const FString& S, const TArray<FString>& Tags, const FConvexValue& Uni, const TOptional<FConvexValue>& Nested, FConvexResultNative OnResult);
	UConvexSubscription* WatchKitchenSink(UConvexClient& Client, const FConvexValue& AnyField, bool B, int64 Big, const TArray<uint8>& By, const TArray<int64>& Counts, const FString& /* Id<documents> */ DocId, double F, const TArray<bool>& Flags, int64 I, const TArray<FConvexValue>& Items, bool LitBool, double LitNum, const FString& LitStr, double N, const FConvexValue& Nul, const TArray<double>& Nums, const FConvexValue& Rec, const FString& S, const TArray<FString>& Tags, const FConvexValue& Uni, const TOptional<FConvexValue>& Nested, FConvexResultNative OnUpdate);

	/// sink.js:noArgs (Query)
	/// args:    object{ }
	/// returns: any
	void NoArgs(UConvexClient& Client, FConvexResultNative OnResult);
	UConvexSubscription* WatchNoArgs(UConvexClient& Client, FConvexResultNative OnUpdate);

	/// sink.js:runAction (Action)
	/// args:    object{ count?: number, uploadId: id<uploads> }
	/// returns: any
	void RunAction(UConvexClient& Client, const FString& /* Id<uploads> */ UploadId, const TOptional<double>& Count, FConvexResultNative OnResult);

}  // namespace Sink

}  // namespace ConvexApi
