// Generated by convex-ue-codegen. Do not edit by hand.
// Source: apispec_full.json (golden fixture)

#include "ConvexApiBP.h"

#include "ConvexClient.h"
#include "ConvexSubscription.h"

DEFINE_LOG_CATEGORY_STATIC(LogConvexApiBP, Log, All);

void UConvexApiAdminToolsLibrary::Reset(UConvexClient* Client, FConvexResultDelegate OnResult)
{
	if (Client == nullptr)
	{
		UE_LOG(LogConvexApiBP, Warning, TEXT("Convex Reset: Client is null"));
		return;
	}
	TMap<FString, FConvexValue> Args;
	Client->Mutation(TEXT("admin/tools:reset"), Args, OnResult);
}

void UConvexApiCountersLibrary::Get(UConvexClient* Client, const FString& Name, FConvexResultDelegate OnResult)
{
	if (Client == nullptr)
	{
		UE_LOG(LogConvexApiBP, Warning, TEXT("Convex Get: Client is null"));
		return;
	}
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("name"), FConvexValue::String(Name));
	Client->Query(TEXT("counters:get"), Args, OnResult);
}

UConvexSubscription* UConvexApiCountersLibrary::WatchGet(UConvexClient* Client, const FString& Name, FConvexResultDelegate OnUpdate)
{
	if (Client == nullptr)
	{
		UE_LOG(LogConvexApiBP, Warning, TEXT("Convex WatchGet: Client is null"));
		return nullptr;
	}
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("name"), FConvexValue::String(Name));
	return Client->Subscribe(TEXT("counters:get"), Args, OnUpdate);
}

void UConvexApiFooBarLibrary::X(UConvexClient* Client, const FString& A, FConvexResultDelegate OnResult)
{
	if (Client == nullptr)
	{
		UE_LOG(LogConvexApiBP, Warning, TEXT("Convex X: Client is null"));
		return;
	}
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("a"), FConvexValue::String(A));
	Client->Query(TEXT("fooBar:x"), Args, OnResult);
}

UConvexSubscription* UConvexApiFooBarLibrary::WatchX(UConvexClient* Client, const FString& A, FConvexResultDelegate OnUpdate)
{
	if (Client == nullptr)
	{
		UE_LOG(LogConvexApiBP, Warning, TEXT("Convex WatchX: Client is null"));
		return nullptr;
	}
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("a"), FConvexValue::String(A));
	return Client->Subscribe(TEXT("fooBar:x"), Args, OnUpdate);
}

void UConvexApiFooBarLibrary::X_2(UConvexClient* Client, const FString& A, FConvexResultDelegate OnResult)
{
	if (Client == nullptr)
	{
		UE_LOG(LogConvexApiBP, Warning, TEXT("Convex X_2: Client is null"));
		return;
	}
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("a"), FConvexValue::String(A));
	Client->Query(TEXT("foo_bar:x"), Args, OnResult);
}

UConvexSubscription* UConvexApiFooBarLibrary::WatchX_2(UConvexClient* Client, const FString& A, FConvexResultDelegate OnUpdate)
{
	if (Client == nullptr)
	{
		UE_LOG(LogConvexApiBP, Warning, TEXT("Convex WatchX_2: Client is null"));
		return nullptr;
	}
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("a"), FConvexValue::String(A));
	return Client->Subscribe(TEXT("foo_bar:x"), Args, OnUpdate);
}

void UConvexApiMessagesLibrary::List(UConvexClient* Client, const FString& Channel, FConvexResultDelegate OnResult)
{
	if (Client == nullptr)
	{
		UE_LOG(LogConvexApiBP, Warning, TEXT("Convex List: Client is null"));
		return;
	}
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("channel"), FConvexValue::String(Channel));
	Client->Query(TEXT("messages:list"), Args, OnResult);
}

UConvexSubscription* UConvexApiMessagesLibrary::WatchList(UConvexClient* Client, const FString& Channel, FConvexResultDelegate OnUpdate)
{
	if (Client == nullptr)
	{
		UE_LOG(LogConvexApiBP, Warning, TEXT("Convex WatchList: Client is null"));
		return nullptr;
	}
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("channel"), FConvexValue::String(Channel));
	return Client->Subscribe(TEXT("messages:list"), Args, OnUpdate);
}

void UConvexApiMessagesLibrary::ListBad(UConvexClient* Client, const FString& Channel, const FConvexValue& PaginationOpts, FConvexResultDelegate OnResult)
{
	if (Client == nullptr)
	{
		UE_LOG(LogConvexApiBP, Warning, TEXT("Convex ListBad: Client is null"));
		return;
	}
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("channel"), FConvexValue::String(Channel));
	Args.Add(TEXT("paginationOpts"), PaginationOpts);
	Client->Query(TEXT("messages:listBad"), Args, OnResult);
}

UConvexSubscription* UConvexApiMessagesLibrary::WatchListBad(UConvexClient* Client, const FString& Channel, const FConvexValue& PaginationOpts, FConvexResultDelegate OnUpdate)
{
	if (Client == nullptr)
	{
		UE_LOG(LogConvexApiBP, Warning, TEXT("Convex WatchListBad: Client is null"));
		return nullptr;
	}
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("channel"), FConvexValue::String(Channel));
	Args.Add(TEXT("paginationOpts"), PaginationOpts);
	return Client->Subscribe(TEXT("messages:listBad"), Args, OnUpdate);
}

void UConvexApiMessagesLibrary::ListPaginated(UConvexClient* Client, const FString& Channel, const FConvexValue& PaginationOpts, FConvexResultDelegate OnResult)
{
	if (Client == nullptr)
	{
		UE_LOG(LogConvexApiBP, Warning, TEXT("Convex ListPaginated: Client is null"));
		return;
	}
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("channel"), FConvexValue::String(Channel));
	Args.Add(TEXT("paginationOpts"), PaginationOpts);
	Client->Query(TEXT("messages:listPaginated"), Args, OnResult);
}

UConvexSubscription* UConvexApiMessagesLibrary::WatchListPaginated(UConvexClient* Client, const FString& Channel, const FConvexValue& PaginationOpts, FConvexResultDelegate OnUpdate)
{
	if (Client == nullptr)
	{
		UE_LOG(LogConvexApiBP, Warning, TEXT("Convex WatchListPaginated: Client is null"));
		return nullptr;
	}
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("channel"), FConvexValue::String(Channel));
	Args.Add(TEXT("paginationOpts"), PaginationOpts);
	return Client->Subscribe(TEXT("messages:listPaginated"), Args, OnUpdate);
}

void UConvexApiSinkLibrary::AnyArgs(UConvexClient* Client, const TMap<FString, FConvexValue>& Args, FConvexResultDelegate OnResult)
{
	if (Client == nullptr)
	{
		UE_LOG(LogConvexApiBP, Warning, TEXT("Convex AnyArgs: Client is null"));
		return;
	}
	Client->Mutation(TEXT("sink:anyArgs"), Args, OnResult);
}

void UConvexApiSinkLibrary::KitchenSink(UConvexClient* Client, const FConvexValue& AnyField, bool B, int64 Big, const TArray<uint8>& By, const TArray<int64>& Counts, const FString& DocId, double F, const TArray<bool>& Flags, int64 I, const TArray<FConvexValue>& Items, bool LitBool, double LitNum, const FString& LitStr, double N, const FConvexValue& Nul, const TArray<double>& Nums, const FConvexValue& Rec, const FString& S, const TArray<FString>& Tags, const FConvexValue& Uni, FConvexResultDelegate OnResult)
{
	if (Client == nullptr)
	{
		UE_LOG(LogConvexApiBP, Warning, TEXT("Convex KitchenSink: Client is null"));
		return;
	}
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("anyField"), AnyField);
	Args.Add(TEXT("b"), FConvexValue::Bool(B));
	Args.Add(TEXT("big"), FConvexValue::Int64(Big));
	Args.Add(TEXT("by"), FConvexValue::Bytes(By));
	{
		TArray<FConvexValue> _CountsItems;
		for (const int64& _Item : Counts)
		{
			_CountsItems.Add(FConvexValue::Int64(_Item));
		}
		Args.Add(TEXT("counts"), FConvexValue::Array(_CountsItems));
	}
	Args.Add(TEXT("docId"), FConvexValue::String(DocId));
	Args.Add(TEXT("f"), FConvexValue::Float(F));
	{
		TArray<FConvexValue> _FlagsItems;
		for (const bool& _Item : Flags)
		{
			_FlagsItems.Add(FConvexValue::Bool(_Item));
		}
		Args.Add(TEXT("flags"), FConvexValue::Array(_FlagsItems));
	}
	Args.Add(TEXT("i"), FConvexValue::Int64(I));
	Args.Add(TEXT("items"), FConvexValue::Array(Items));
	Args.Add(TEXT("litBool"), FConvexValue::Bool(LitBool));
	Args.Add(TEXT("litNum"), FConvexValue::Float(LitNum));
	Args.Add(TEXT("litStr"), FConvexValue::String(LitStr));
	Args.Add(TEXT("n"), FConvexValue::Float(N));
	Args.Add(TEXT("nul"), Nul);
	{
		TArray<FConvexValue> _NumsItems;
		for (const double& _Item : Nums)
		{
			_NumsItems.Add(FConvexValue::Float(_Item));
		}
		Args.Add(TEXT("nums"), FConvexValue::Array(_NumsItems));
	}
	Args.Add(TEXT("rec"), Rec);
	Args.Add(TEXT("s"), FConvexValue::String(S));
	{
		TArray<FConvexValue> _TagsItems;
		for (const FString& _Item : Tags)
		{
			_TagsItems.Add(FConvexValue::String(_Item));
		}
		Args.Add(TEXT("tags"), FConvexValue::Array(_TagsItems));
	}
	Args.Add(TEXT("uni"), Uni);
	Client->Query(TEXT("sink:kitchenSink"), Args, OnResult);
}

UConvexSubscription* UConvexApiSinkLibrary::WatchKitchenSink(UConvexClient* Client, const FConvexValue& AnyField, bool B, int64 Big, const TArray<uint8>& By, const TArray<int64>& Counts, const FString& DocId, double F, const TArray<bool>& Flags, int64 I, const TArray<FConvexValue>& Items, bool LitBool, double LitNum, const FString& LitStr, double N, const FConvexValue& Nul, const TArray<double>& Nums, const FConvexValue& Rec, const FString& S, const TArray<FString>& Tags, const FConvexValue& Uni, FConvexResultDelegate OnUpdate)
{
	if (Client == nullptr)
	{
		UE_LOG(LogConvexApiBP, Warning, TEXT("Convex WatchKitchenSink: Client is null"));
		return nullptr;
	}
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("anyField"), AnyField);
	Args.Add(TEXT("b"), FConvexValue::Bool(B));
	Args.Add(TEXT("big"), FConvexValue::Int64(Big));
	Args.Add(TEXT("by"), FConvexValue::Bytes(By));
	{
		TArray<FConvexValue> _CountsItems;
		for (const int64& _Item : Counts)
		{
			_CountsItems.Add(FConvexValue::Int64(_Item));
		}
		Args.Add(TEXT("counts"), FConvexValue::Array(_CountsItems));
	}
	Args.Add(TEXT("docId"), FConvexValue::String(DocId));
	Args.Add(TEXT("f"), FConvexValue::Float(F));
	{
		TArray<FConvexValue> _FlagsItems;
		for (const bool& _Item : Flags)
		{
			_FlagsItems.Add(FConvexValue::Bool(_Item));
		}
		Args.Add(TEXT("flags"), FConvexValue::Array(_FlagsItems));
	}
	Args.Add(TEXT("i"), FConvexValue::Int64(I));
	Args.Add(TEXT("items"), FConvexValue::Array(Items));
	Args.Add(TEXT("litBool"), FConvexValue::Bool(LitBool));
	Args.Add(TEXT("litNum"), FConvexValue::Float(LitNum));
	Args.Add(TEXT("litStr"), FConvexValue::String(LitStr));
	Args.Add(TEXT("n"), FConvexValue::Float(N));
	Args.Add(TEXT("nul"), Nul);
	{
		TArray<FConvexValue> _NumsItems;
		for (const double& _Item : Nums)
		{
			_NumsItems.Add(FConvexValue::Float(_Item));
		}
		Args.Add(TEXT("nums"), FConvexValue::Array(_NumsItems));
	}
	Args.Add(TEXT("rec"), Rec);
	Args.Add(TEXT("s"), FConvexValue::String(S));
	{
		TArray<FConvexValue> _TagsItems;
		for (const FString& _Item : Tags)
		{
			_TagsItems.Add(FConvexValue::String(_Item));
		}
		Args.Add(TEXT("tags"), FConvexValue::Array(_TagsItems));
	}
	Args.Add(TEXT("uni"), Uni);
	return Client->Subscribe(TEXT("sink:kitchenSink"), Args, OnUpdate);
}

void UConvexApiSinkLibrary::NoArgs(UConvexClient* Client, FConvexResultDelegate OnResult)
{
	if (Client == nullptr)
	{
		UE_LOG(LogConvexApiBP, Warning, TEXT("Convex NoArgs: Client is null"));
		return;
	}
	TMap<FString, FConvexValue> Args;
	Client->Query(TEXT("sink:noArgs"), Args, OnResult);
}

UConvexSubscription* UConvexApiSinkLibrary::WatchNoArgs(UConvexClient* Client, FConvexResultDelegate OnUpdate)
{
	if (Client == nullptr)
	{
		UE_LOG(LogConvexApiBP, Warning, TEXT("Convex WatchNoArgs: Client is null"));
		return nullptr;
	}
	TMap<FString, FConvexValue> Args;
	return Client->Subscribe(TEXT("sink:noArgs"), Args, OnUpdate);
}

void UConvexApiSinkLibrary::RunAction(UConvexClient* Client, const FString& UploadId, FConvexResultDelegate OnResult)
{
	if (Client == nullptr)
	{
		UE_LOG(LogConvexApiBP, Warning, TEXT("Convex RunAction: Client is null"));
		return;
	}
	TMap<FString, FConvexValue> Args;
	Args.Add(TEXT("uploadId"), FConvexValue::String(UploadId));
	Client->Action(TEXT("sink:runAction"), Args, OnResult);
}

