// Generated by convex-ue-codegen. Do not edit by hand.
// Source: apispec_full.json (golden fixture)

#pragma once

// Blueprint-callable wrappers for the deployed Convex functions.
// These files only compile inside a UE module (UHT-processed).

#include "CoreMinimal.h"
#include "Kismet/BlueprintFunctionLibrary.h"
#include "ConvexValue.h"
#include "ConvexDelegates.h"

#include "ConvexApiBP.generated.h"

class UConvexClient;
class UConvexSubscription;

UCLASS()
class UConvexApiAdminToolsLibrary : public UBlueprintFunctionLibrary
{
	GENERATED_BODY()

public:
	UFUNCTION(BlueprintCallable, Category = "Convex API|admin/tools", meta = (DisplayName = "Convex admin/tools:reset", ToolTip = "admin/tools:reset (Mutation)\nargs: object{ force?: boolean }\noptional args omitted; use the C++ wrapper"))
	static void Reset(UConvexClient* Client, FConvexResultDelegate OnResult);

};

UCLASS()
class UConvexApiFooBarLibrary : public UBlueprintFunctionLibrary
{
	GENERATED_BODY()

public:
	UFUNCTION(BlueprintCallable, Category = "Convex API|fooBar", meta = (DisplayName = "Convex fooBar:x", ToolTip = "fooBar:x (Query)\nargs: object{ a: string }"))
	static void X(UConvexClient* Client, const FString& A, FConvexResultDelegate OnResult);

	UFUNCTION(BlueprintCallable, Category = "Convex API|fooBar", meta = (DisplayName = "Convex Watch fooBar:x", ToolTip = "fooBar:x (Query) live subscription\nargs: object{ a: string }"))
	static UConvexSubscription* WatchX(UConvexClient* Client, const FString& A, FConvexResultDelegate OnUpdate);

	UFUNCTION(BlueprintCallable, Category = "Convex API|fooBar", meta = (DisplayName = "Convex foo_bar:x", ToolTip = "foo_bar:x (Query)\nargs: object{ a: string }"))
	static void X_2(UConvexClient* Client, const FString& A, FConvexResultDelegate OnResult);

	UFUNCTION(BlueprintCallable, Category = "Convex API|fooBar", meta = (DisplayName = "Convex Watch foo_bar:x", ToolTip = "foo_bar:x (Query) live subscription\nargs: object{ a: string }"))
	static UConvexSubscription* WatchX_2(UConvexClient* Client, const FString& A, FConvexResultDelegate OnUpdate);

};

UCLASS()
class UConvexApiSinkLibrary : public UBlueprintFunctionLibrary
{
	GENERATED_BODY()

public:
	UFUNCTION(BlueprintCallable, Category = "Convex API|sink", meta = (DisplayName = "Convex sink:anyArgs", ToolTip = "sink:anyArgs (Mutation)\nargs: any"))
	static void AnyArgs(UConvexClient* Client, const TMap<FString, FConvexValue>& Args, FConvexResultDelegate OnResult);

	UFUNCTION(BlueprintCallable, Category = "Convex API|sink", meta = (DisplayName = "Convex sink:kitchenSink", ToolTip = "sink:kitchenSink (Query)\nargs: object{ anyField: any, b: boolean, big: bigint, by: bytes, counts: array<int64>, docId: id<documents>, f: float64, flags: array<boolean>, i: int64, items: array<object{ id: string, qty: int64 }>, litBool: literal(true), litNum: literal(42), litStr: literal("hello"), n: number, nested?: object{ deep?: object{ x: number }, inner: string }, nul: null, nums: array<number>, rec: record<string, number>, s: string, tags: array<string>, uni: union<string | number | object{ k: boolean }> }\noptional args omitted; use the C++ wrapper"))
	static void KitchenSink(UConvexClient* Client, const FConvexValue& AnyField, bool B, int64 Big, const TArray<uint8>& By, const TArray<int64>& Counts, const FString& DocId, double F, const TArray<bool>& Flags, int64 I, const TArray<FConvexValue>& Items, bool LitBool, double LitNum, const FString& LitStr, double N, const FConvexValue& Nul, const TArray<double>& Nums, const FConvexValue& Rec, const FString& S, const TArray<FString>& Tags, const FConvexValue& Uni, FConvexResultDelegate OnResult);

	UFUNCTION(BlueprintCallable, Category = "Convex API|sink", meta = (DisplayName = "Convex Watch sink:kitchenSink", ToolTip = "sink:kitchenSink (Query) live subscription\nargs: object{ anyField: any, b: boolean, big: bigint, by: bytes, counts: array<int64>, docId: id<documents>, f: float64, flags: array<boolean>, i: int64, items: array<object{ id: string, qty: int64 }>, litBool: literal(true), litNum: literal(42), litStr: literal("hello"), n: number, nested?: object{ deep?: object{ x: number }, inner: string }, nul: null, nums: array<number>, rec: record<string, number>, s: string, tags: array<string>, uni: union<string | number | object{ k: boolean }> }\noptional args omitted; use the C++ wrapper"))
	static UConvexSubscription* WatchKitchenSink(UConvexClient* Client, const FConvexValue& AnyField, bool B, int64 Big, const TArray<uint8>& By, const TArray<int64>& Counts, const FString& DocId, double F, const TArray<bool>& Flags, int64 I, const TArray<FConvexValue>& Items, bool LitBool, double LitNum, const FString& LitStr, double N, const FConvexValue& Nul, const TArray<double>& Nums, const FConvexValue& Rec, const FString& S, const TArray<FString>& Tags, const FConvexValue& Uni, FConvexResultDelegate OnUpdate);

	UFUNCTION(BlueprintCallable, Category = "Convex API|sink", meta = (DisplayName = "Convex sink:noArgs", ToolTip = "sink:noArgs (Query)\nargs: object{ }"))
	static void NoArgs(UConvexClient* Client, FConvexResultDelegate OnResult);

	UFUNCTION(BlueprintCallable, Category = "Convex API|sink", meta = (DisplayName = "Convex Watch sink:noArgs", ToolTip = "sink:noArgs (Query) live subscription\nargs: object{ }"))
	static UConvexSubscription* WatchNoArgs(UConvexClient* Client, FConvexResultDelegate OnUpdate);

	UFUNCTION(BlueprintCallable, Category = "Convex API|sink", meta = (DisplayName = "Convex sink:runAction", ToolTip = "sink:runAction (Action)\nargs: object{ count?: number, uploadId: id<uploads> }\noptional args omitted; use the C++ wrapper"))
	static void RunAction(UConvexClient* Client, const FString& UploadId, FConvexResultDelegate OnResult);

};

